### ISSUE TITLE
Memory overwrite

### ISSUE THREAD

**Issue by jonesmGatcom** [analogdevicesinc/ad9361#1]
In current master repo.  In sw\platform_xilinx\dac_core.c::dac_datasel there is the potential for memory overwrite when the option to the function has the channel set to -1 for all channels, due to this line of code:
dds_st[phy->id_no].cached_datasel[chan] = sel;

Because the index to the cached_datasel array will be negative one, through chan, the input arg being set to negative 1.  Looks like this function needs to consider the case of negative one being all channels appropriately when writing back the settings to the cached_datasel array.

**Comment by jonesmGatcom** [comment]
The effect will be that the cached_scale[7] value is corrupted, in the dds_st structure, because it is one index behind the cached_datasel array start.

**Comment by dbogdan** [comment]
The issue was fixed. Thanks for let us know.

**Comment by jonesmGatcom** [comment]
Sure no problem.  Glad to help out, we appreciate the example code ;)

Matthew Jones
Software Engineering
General Atomics Aeronautical Systems, Inc
14200 Kirkham way
Poway, CA 02964

Office: 858-312-4690
Email: jonesm@gat.com
